### ISSUE TITLE
not an issue just: new  proposal for modp_stdint.h again

### ISSUE THREAD

**Issue by GoogleCodeExporter** [client9/stringencoders#41]
```
again 8) happy new year!
```

Original issue reported on code.google.com by `0xcafef...@gmail.com` on 17 Feb 2015 at 1:01

Attachments:
* [modp_stdint.h](https://storage.googleapis.com/google-code-attachments/stringencoders/issue-41/comment-0/modp_stdint.h)

**Comment by client9** [comment]
pull requests welcome.
